# Generated by Django 6.0.4 on 2026-04-18 20:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_exhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.CharField(blank=True, max_length=100, null=True)),
                ('blend', models.CharField(blank=True, max_length=100, null=True)),
                ('shade', models.CharField(blank=True, max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list)),
                ('supplier_id', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
